# Generated by Django 5.1.6 on 2025-04-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_savednews_article_source_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_summarized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
