# Generated by Django 5.1.6 on 2025-04-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsarticle_is_summarized_newsarticle_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='is_summarized',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
