# Generated by Django 5.1.6 on 2025-04-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_newsarticle_is_summarized_newsarticle_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='full_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
